baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
googleAnalytics = "UA-64145097-4"

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "CS373 Fall 2020: Shrivu Shankar"
    subtitle = "A blog for CS373."
    keywords = "cs373"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "CS373 Fall 2020: Shrivu Shankar"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "website"
        name = "Website"
        url = "https://sshh.io"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/sshh12"
      